const champions = [
  // 1-cost champions
  { name: "Anivia", cost: 1, traits: ["Freljord", "Invoker"] },
  { name: "Blitzcrank", cost: 1, traits: ["Zaun", "Juggernaut"] },
  { name: "Briar", cost: 1, traits: ["Noxus", "Juggernaut", "Slayer"] },
  { name: "Caitlyn", cost: 1, traits: ["Piltover", "Longshot"] },
  { name: "Illaoi", cost: 1, traits: ["Bilgewater", "Bruiser"] },
  { name: "Jarvan IV", cost: 1, traits: ["Demacia", "Defender"] },
  { name: "Jhin", cost: 1, traits: ["Ionia", "Gunslinger"] },
  { name: "Kog'Maw", cost: 1, traits: ["Void", "Arcanist", "Longshot"] },
  { name: "Lulu", cost: 1, traits: ["Yordle", "Arcanist"] },
  { name: "Qiyana", cost: 1, traits: ["Ixtal", "Slayer"] },
  { name: "Rumble", cost: 1, traits: ["Yordle", "Defender"] },
  { name: "Shen", cost: 1, traits: ["Ionia", "Bruiser"] },
  { name: "Sona", cost: 1, traits: ["Demacia", "Invoker"] },
  { name: "Viego", cost: 1, traits: ["Shadow Isles", "Quickstriker"] },

  // 2-cost champions
  { name: "Aphelios", cost: 2, traits: ["Targon"] },
  { name: "Ashe", cost: 2, traits: ["Freljord", "Quickstriker"] },
  { name: "Bard", cost: 2, traits: ["Caretaker"], unlockable: true },
  { name: "Cho'Gath", cost: 2, traits: ["Void", "Juggernaut"] },
  { name: "Ekko", cost: 2, traits: ["Zaun", "Disruptor"] },
  { name: "Graves", cost: 2, traits: ["Bilgewater", "Gunslinger"], unlockable: true },
  { name: "Neeko", cost: 2, traits: ["Ixtal", "Arcanist", "Defender"] },
  { name: "Orianna", cost: 2, traits: ["Piltover", "Invoker"], unlockable: true },
  { name: "Poppy", cost: 2, traits: ["Demacia", "Yordle", "Juggernaut"], unlockable: true },
  { name: "Rek'Sai", cost: 2, traits: ["Void", "Vanquisher"] },
  { name: "Sion", cost: 2, traits: ["Noxus", "Bruiser"] },
  { name: "Teemo", cost: 2, traits: ["Yordle", "Longshot"] },
  { name: "Tristana", cost: 2, traits: ["Yordle", "Gunslinger"] },
  { name: "Tryndamere", cost: 2, traits: ["Freljord", "Slayer"], unlockable: true },
  { name: "Twisted Fate", cost: 2, traits: ["Bilgewater", "Quickstriker"] },
  { name: "Vi", cost: 2, traits: ["Piltover", "Zaun", "Defender"] },
  { name: "Xin Zhao", cost: 2, traits: ["Demacia", "Ionia", "Warden"] },
  { name: "Yasuo", cost: 2, traits: ["Ionia", "Slayer"] },
  { name: "Yorick", cost: 2, traits: ["Shadow Isles", "Warden"], unlockable: true },

  // 3-cost champions
  { name: "Ahri", cost: 3, traits: ["Ionia", "Arcanist"] },
  { name: "Darius", cost: 3, traits: ["Noxus", "Defender"], unlockable: true },
  { name: "Dr. Mundo", cost: 3, traits: ["Zaun", "Bruiser"] },
  { name: "Draven", cost: 3, traits: ["Noxus", "Quickstriker"] },
  { name: "Gangplank", cost: 3, traits: ["Bilgewater", "Slayer", "Vanquisher"] },
  { name: "Gwen", cost: 3, traits: ["Shadow Isles", "Disruptor"], unlockable: true },
  { name: "Jinx", cost: 3, traits: ["Zaun", "Gunslinger"] },
  { name: "Kennen", cost: 3, traits: ["Ionia", "Yordle", "Defender"], unlockable: true },
  { name: "Kobuko & Yuumi", cost: 3, traits: ["Yordle", "Bruiser", "Invoker"], unlockable: true },
  { name: "LeBlanc", cost: 3, traits: ["Noxus", "Invoker"] },
  { name: "Leona", cost: 3, traits: ["Targon"] },
  { name: "Loris", cost: 3, traits: ["Piltover", "Warden"] },
  { name: "Malzahar", cost: 3, traits: ["Void", "Disruptor"] },
  { name: "Milio", cost: 3, traits: ["Ixtal", "Invoker"] },
  { name: "Nautilus", cost: 3, traits: ["Bilgewater", "Juggernaut", "Warden"] },
  { name: "Sejuani", cost: 3, traits: ["Freljord", "Defender"] },
  { name: "Vayne", cost: 3, traits: ["Demacia", "Longshot"] },
  { name: "Zoe", cost: 3, traits: ["Targon"] },

  // 4-cost champions
  { name: "Ambessa", cost: 4, traits: ["Noxus", "Vanquisher"] },
  { name: "Bel'Veth", cost: 4, traits: ["Void", "Slayer"] },
  { name: "Braum", cost: 4, traits: ["Freljord", "Warden"] },
  { name: "Diana", cost: 4, traits: ["Targon"], unlockable: true },
  { name: "Fizz", cost: 4, traits: ["Bilgewater", "Yordle"], unlockable: true },
  { name: "Garen", cost: 4, traits: ["Demacia", "Defender"] },
  { name: "Kai'Sa", cost: 4, traits: ["Assimilator", "Void", "Longshot"], unlockable: true },
  { name: "Kalista", cost: 4, traits: ["Shadow Isles", "Vanquisher"], unlockable: true },
  { name: "Lissandra", cost: 4, traits: ["Freljord", "Invoker"] },
  { name: "Lux", cost: 4, traits: ["Demacia", "Arcanist"] },
  { name: "Miss Fortune", cost: 4, traits: ["Bilgewater", "Gunslinger"] },
  { name: "Nasus", cost: 4, traits: ["Shurima"], unlockable: true },
  { name: "Nidalee", cost: 4, traits: ["Ixtal", "Huntress"], unlockable: true },
  { name: "Renekton", cost: 4, traits: ["Shurima"], unlockable: true },
  { name: "Rift Herald", cost: 4, traits: ["Void", "Bruiser"], unlockable: true },
  { name: "Seraphine", cost: 4, traits: ["Piltover", "Disruptor"] },
  { name: "Singed", cost: 4, traits: ["Zaun", "Juggernaut"], unlockable: true },
  { name: "Skarner", cost: 4, traits: ["Ixtal"], unlockable: true },
  { name: "Swain", cost: 4, traits: ["Noxus", "Arcanist", "Juggernaut"] },
  { name: "Taric", cost: 4, traits: ["Targon"] },
  { name: "Veigar", cost: 4, traits: ["Yordle", "Arcanist"], unlockable: true },
  { name: "Warwick", cost: 4, traits: ["Zaun", "Quickstriker"], unlockable: true },
  { name: "Wukong", cost: 4, traits: ["Ionia", "Bruiser"] },
  { name: "Yone", cost: 4, traits: ["Ionia", "Slayer"], unlockable: true },
  { name: "Yunara", cost: 4, traits: ["Ionia", "Quickstriker"] },

  // 5-cost champions
  { name: "Aatrox", cost: 5, traits: ["Darkin", "World Ender", "Slayer"], unlockable: true },
  { name: "Annie", cost: 5, traits: ["Dark Child", "Arcanist"] },
  { name: "Azir", cost: 5, traits: ["Emperor", "Shurima", "Disruptor"] },
  { name: "Fiddlesticks", cost: 5, traits: ["Harvester", "Vanquisher"] },
  { name: "Galio", cost: 5, traits: ["Demacia", "Heroic"], unlockable: true },
  { name: "Kindred", cost: 5, traits: ["Eternal", "Quickstriker"] },
  { name: "Lucian & Senna", cost: 5, traits: ["Soulbound", "Gunslinger"] },
  { name: "Mel", cost: 5, traits: ["Noxus", "Disruptor"], unlockable: true },
  { name: "Ornn", cost: 5, traits: ["Blacksmith", "Warden"] },
  { name: "Sett", cost: 5, traits: ["Ionia", "The Boss"], unlockable: true },
  { name: "Shyvana", cost: 5, traits: ["Dragonborn", "Juggernaut"] },
  { name: "T-Hex", cost: 5, traits: ["HexMech", "Piltover", "Gunslinger"], unlockable: true },
  { name: "Tahm Kench", cost: 5, traits: ["Bilgewater", "Glutton", "Bruiser"], unlockable: true },
  { name: "Thresh", cost: 5, traits: ["Shadow Isles", "Warden"], unlockable: true },
  { name: "Volibear", cost: 5, traits: ["Freljord", "Bruiser"], unlockable: true },
  { name: "Xerath", cost: 5, traits: ["Shurima", "Ascendant"], unlockable: true },
  { name: "Ziggs", cost: 5, traits: ["Yordle", "Zaun", "Longshot"], unlockable: true },
  { name: "Zilean", cost: 5, traits: ["Chronokeeper", "Invoker"] },

  // 7-cost champions
  { name: "Aurelion Sol", cost: 7, traits: ["Targon", "Star Forger"], unlockable: true },
  { name: "Baron Nashor", cost: 7, traits: ["Void", "Riftscourge"], unlockable: true },
  { name: "Brock", cost: 7, traits: ["Ixtal"], unlockable: true },
  { name: "Ryze", cost: 7, traits: ["Rune Mage"], unlockable: true },
  { name: "Sylas", cost: 7, traits: ["Chainbreaker", "Arcanist", "Defender"], unlockable: true },
  { name: "Zaahen", cost: 7, traits: ["Darkin", "Immortal"], unlockable: true },
];

// Synergies/Traits with thresholds
const synergies = {
  // Classes
  'Arcanist': { thresholds: [2, 4, 6, 8], type: 'class' },
  'Bruiser': { thresholds: [2, 4, 6], type: 'class' },
  'Defender': { thresholds: [2, 4, 6], type: 'class' },
  'Disruptor': { thresholds: [2, 4, 6], type: 'class' },
  'Gunslinger': { thresholds: [2, 4, 6], type: 'class' },
  'Invoker': { thresholds: [2, 4, 6], type: 'class' },
  'Juggernaut': { thresholds: [2, 4, 6], type: 'class' },
  'Longshot': { thresholds: [2, 4, 6], type: 'class' },
  'Quickstriker': { thresholds: [2, 4, 6], type: 'class' },
  'Slayer': { thresholds: [2, 4, 6], type: 'class' },
  'Vanquisher': { thresholds: [2, 4], type: 'class' },
  'Warden': { thresholds: [2, 4, 6], type: 'class' },

  // Regions/Origins
  'Bilgewater': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Demacia': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Freljord': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Ionia': { thresholds: [3, 5, 7], type: 'origin' },
  'Ixtal': { thresholds: [3, 5, 7], type: 'origin' },
  'Noxus': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Piltover': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Shadow Isles': { thresholds: [2, 4, 6, 8], type: 'origin' },
  'Shurima': { thresholds: [2, 4, 6], type: 'origin' },
  'Targon': { thresholds: [2, 4, 6], type: 'origin' },
  'Void': { thresholds: [3, 5, 7], type: 'origin' },
  'Yordle': { thresholds: [2, 4, 6], type: 'origin' },
  'Zaun': { thresholds: [2, 4, 6], type: 'origin' },

  // Unique traits
  'Ascendant': { thresholds: [1], type: 'unique' },
  'Assimilator': { thresholds: [1], type: 'unique' },
  'Blacksmith': { thresholds: [1], type: 'unique' },
  'Caretaker': { thresholds: [1], type: 'unique' },
  'Chainbreaker': { thresholds: [1], type: 'unique' },
  'Chronokeeper': { thresholds: [1], type: 'unique' },
  'Dark Child': { thresholds: [1], type: 'unique' },
  'Darkin': { thresholds: [2], type: 'unique' },
  'Dragonborn': { thresholds: [1], type: 'unique' },
  'Emperor': { thresholds: [1], type: 'unique' },
  'Eternal': { thresholds: [1], type: 'unique' },
  'Glutton': { thresholds: [1], type: 'unique' },
  'Harvester': { thresholds: [1], type: 'unique' },
  'Heroic': { thresholds: [1], type: 'unique' },
  'HexMech': { thresholds: [1], type: 'unique' },
  'Huntress': { thresholds: [1], type: 'unique' },
  'Immortal': { thresholds: [1], type: 'unique' },
  'Riftscourge': { thresholds: [1], type: 'unique' },
  'Rune Mage': { thresholds: [1], type: 'unique' },
  'Soulbound': { thresholds: [1], type: 'unique' },
  'Star Forger': { thresholds: [1], type: 'unique' },
  'The Boss': { thresholds: [1], type: 'unique' },
  'World Ender': { thresholds: [1], type: 'unique' },
};