const champions = [
  // 1-cost
  { name: 'Anivia', cost: 1, traits: ['Freljord', 'Invoker'] },
  { name: 'Blitzcrank', cost: 1, traits: ['Zaun', 'Juggernaut'] },
  { name: 'Briar', cost: 1, traits: ['Noxus', 'Juggernaut', 'Slayer'] },
  { name: 'Caitlyn', cost: 1, traits: ['Piltover', 'Longshot'] },
  { name: 'Illaoi', cost: 1, traits: ['Bilgewater', 'Bruiser'] },
  { name: 'Jarvan IV', cost: 1, traits: ['Demacia', 'Defender'] },
  { name: 'Jhin', cost: 1, traits: ['Ionia', 'Gunslinger'] },
  { name: 'Kog\'Maw', cost: 1, traits: ['Void', 'Arcanist', 'Longshot'] },
  { name: 'Lulu', cost: 1, traits: ['Yordle', 'Arcanist'] },
  { name: 'Qiyana', cost: 1, traits: ['Ixtal', 'Slayer'] },
  { name: 'Rumble', cost: 1, traits: ['Yordle', 'Defender'] },
  { name: 'Shen', cost: 1, traits: ['Ionia', 'Bruiser'] },
  { name: 'Sona', cost: 1, traits: ['Demacia', 'Invoker'] },
  { name: 'Viego', cost: 1, traits: ['Shadow Isles', 'Quickstriker'] },
  // 2-cost
  { name: 'Aphelios', cost: 2, traits: ['Targon'] },
  { name: 'Ashe', cost: 2, traits: ['Freljord', 'Quickstriker'] },
  { name: 'Cho\'Gath', cost: 2, traits: ['Void', 'Juggernaut'] },
  { name: 'Ekko', cost: 2, traits: ['Zaun', 'Disruptor'] },
  { name: 'Neeko', cost: 2, traits: ['Ixtal', 'Arcanist', 'Defender'] },
  { name: 'Rek\'Sai', cost: 2, traits: ['Void', 'Vanquisher'] },
  { name: 'Sion', cost: 2, traits: ['Noxus', 'Bruiser'] },
  { name: 'Teemo', cost: 2, traits: ['Yordle', 'Longshot'] },
  { name: 'Tristana', cost: 2, traits: ['Yordle', 'Gunslinger'] },
  { name: 'Twisted Fate', cost: 2, traits: ['Bilgewater', 'Quickstriker'] },
  { name: 'Vi', cost: 2, traits: ['Piltover', 'Zaun', 'Defender'] },
  { name: 'Xin Zhao', cost: 2, traits: ['Demacia', 'Ionia', 'Warden'] },
  { name: 'Yasuo', cost: 2, traits: ['Ionia', 'Slayer'] },
  // 3-cost
  { name: 'Ahri', cost: 3, traits: ['Ionia', 'Arcanist'] },
  { name: 'Dr. Mundo', cost: 3, traits: ['Zaun', 'Bruiser'] },
  { name: 'Draven', cost: 3, traits: ['Noxus', 'Quickstriker'] },
  { name: 'Gangplank', cost: 3, traits: ['Bilgewater', 'Slayer', 'Vanquisher'] },
  { name: 'Jinx', cost: 3, traits: ['Zaun', 'Gunslinger'] },
  { name: 'LeBlanc', cost: 3, traits: ['Noxus', 'Invoker'] },
  { name: 'Leona', cost: 3, traits: ['Targon'] },
  { name: 'Loris', cost: 3, traits: ['Piltover', 'Warden'] },
  { name: 'Malzahar', cost: 3, traits: ['Void', 'Disruptor'] },
  { name: 'Milio', cost: 3, traits: ['Ixtal', 'Invoker'] },
  { name: 'Nautilus', cost: 3, traits: ['Bilgewater', 'Juggernaut', 'Warden'] },
  { name: 'Sejuani', cost: 3, traits: ['Freljord', 'Defender'] },
  { name: 'Vayne', cost: 3, traits: ['Demacia', 'Longshot'] },
  { name: 'Zoe', cost: 3, traits: ['Targon'] },
  // 4-cost
  { name: 'Ambessa', cost: 4, traits: ['Noxus', 'Vanquisher'] },
  { name: 'Bel\'Veth', cost: 4, traits: ['Void', 'Slayer'] },
  { name: 'Braum', cost: 4, traits: ['Freljord', 'Warden'] },
  { name: 'Garen', cost: 4, traits: ['Demacia', 'Defender'] },
  { name: 'Lissandra', cost: 4, traits: ['Freljord', 'Invoker'] },
  { name: 'Lux', cost: 4, traits: ['Demacia', 'Arcanist'] },
  { name: 'Miss Fortune', cost: 4, traits: ['Bilgewater', 'Gunslinger'] },
  { name: 'Seraphine', cost: 4, traits: ['Piltover', 'Disruptor'] },
  { name: 'Swain', cost: 4, traits: ['Noxus', 'Arcanist', 'Juggernaut'] },
  { name: 'Taric', cost: 4, traits: ['Targon'] },
  { name: 'Wukong', cost: 4, traits: ['Ionia', 'Bruiser'] },
  { name: 'Yunara', cost: 4, traits: ['Ionia', 'Quickstriker'] },
  // 5-cost
  { name: 'Annie', cost: 5, traits: ['Dark Child', 'Arcanist'] },
  { name: 'Azir', cost: 5, traits: ['Emperor', 'Shurima', 'Disruptor'] },
  { name: 'Fiddlesticks', cost: 5, traits: ['Harvester', 'Vanquisher'] },
  { name: 'Kindred', cost: 5, traits: ['Eternal', 'Quickstriker'] },
  { name: 'Lucian & Senna', cost: 5, traits: ['Soulbound', 'Gunslinger'] },
  { name: 'Ornn', cost: 5, traits: ['Blacksmith', 'Warden'] },
  { name: 'Shyvana', cost: 5, traits: ['Dragonborn', 'Juggernaut'] },
  { name: 'Zilean', cost: 5, traits: ['Chronokeeper', 'Invoker'] },
];

// Synergies with thresholds
const synergies = {
  // Classes
  'Arcanist': { thresholds: [2, 4, 6, 8], type: 'class' },
  'Ascendant': { thresholds: [1], type: 'class' },
  'Bruiser': { thresholds: [2, 4, 6], type: 'class' },
  'Defender': { thresholds: [2, 4, 6], type: 'class' },
  'Disruptor': { thresholds: [2, 4, 6], type: 'class' },
  'Gunslinger': { thresholds: [2, 4, 6], type: 'class' },
  'Huntress': { thresholds: [1], type: 'class' },
  'Invoker': { thresholds: [2, 4, 6], type: 'class' },
  'Juggernaut': { thresholds: [2, 4, 6], type: 'class' },
  'Longshot': { thresholds: [2, 4, 6], type: 'class' },
  'Quickstriker': { thresholds: [2, 4, 6], type: 'class' },
  'Slayer': { thresholds: [2, 4, 6], type: 'class' },
  'Vanquisher': { thresholds: [2, 4], type: 'class' },
  'Warden': { thresholds: [2, 4, 6], type: 'class' },
  // Regions
  'Bilgewater': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Blacksmith': { thresholds: [1], type: 'origin' },
  'Chronokeeper': { thresholds: [1], type: 'origin' },
  'Dark Child': { thresholds: [1], type: 'origin' },
  'Demacia': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Dragonborn': { thresholds: [1], type: 'origin' },
  'Emperor': { thresholds: [1], type: 'origin' },
  'Eternal': { thresholds: [1], type: 'origin' },
  'Freljord': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Harvester': { thresholds: [1], type: 'origin' },
  'Ionia': { thresholds: [3, 5, 7], type: 'origin' },
  'Ixtal': { thresholds: [3, 5, 7], type: 'origin' },
  'Noxus': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Piltover': { thresholds: [3, 5, 7, 9], type: 'origin' },
  'Shadow Isles': { thresholds: [2, 4, 6, 8], type: 'origin' },
  'Shurima': { thresholds: [2, 4, 6], type: 'origin' },
  'Soulbound': { thresholds: [1], type: 'origin' },
  'Targon': { thresholds: [2, 4, 6], type: 'origin' },
  'Void': { thresholds: [3, 5, 7], type: 'origin' },
  'Yordle': { thresholds: [2, 4, 6], type: 'origin' },
  'Zaun': { thresholds: [2, 4, 6], type: 'origin' },
};